### ISSUE TITLE
Avast Detect Nintendulator.exe as a virus Win32:MalOb-CA [Cryp]

### ISSUE THREAD

**Issue by XxhamoodZX** [quietust/nintendulator#10]
![Virus](https://github.com/quietust/nintendulator/assets/141411318/ec576b02-d6a2-4bcb-9b72-c8fa81073bed)

**Comment by quietust** [comment]
Either it's a false positive, or you obtained the binaries from an untrusted location - I just scanned the latest beta build with Windows Defender and it came up clean.
