### ISSUE TITLE
Emulator runs at insane 200 FPS

### ISSUE THREAD

**Issue by ElektroStudios** [quietust/nintendulator#11]
First of all I want to thank you for developing and sharing the emulator.

I just downloaded this emulator to try, but any game that I load in this emulator it runs at around 200 FPS, insanely fast, It can't be played.

The first thing I did when I saw that, was to look for an FSP cap option in the program options, but I didn't found it. Frameskip and slowdown options does not solve this issue.

This happens to me in both x64 and x86 executable files, in the latest beta and the latest stable release.

I imagine that the author of the emulator is unaware of this problem, because if there are no options to limit the FPS to 30 or 60...

So I also think that this problem will not happen to everyone, that's why I give the specifications of my computer below:

Operating System: Windows 10.0.19045.2006 (also known as [version 22H2](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_22H2_(2022_Update))) x64

CPU: AMD Ryzen 7 1700X (chipset X370, 8 cores)
GPU: nVidia GTX 1060 6GB
RAM: 4GB x4 slots (16 GB), Single-Channel DDR4
Motherboard: ASUS PRIME X370-PRO (AM4)
Monitor: LG 24MP58VQ-P (year 2017)

![WinSnap 01](https://github.com/quietust/nintendulator/assets/13082613/590aabd3-9382-447d-af57-b2dfac8a9429)

I have tried Ares, BizHawk, FCEUX, Mesen 2, Nestopia UE and puNES, I can say the FPS issue is only present with Nintendulator.

If I enable slowdown (TAB) and the slowdown option "1/2 (50%)" and I also set frameskip to 0, it runs at 18-20 FPS, too slow.

**Comment by quietust** [comment]
In order to run at "normal" speed, Sound must be turned **on**, even if only at 0% volume - turning off sound disables speed throttling.

**Comment by ElektroStudios** [comment]
I disabled the sound, that was the problem, thank a lot. Now it runs at "normal" speed with the sound enabled and "mute" checkbox checked.
