### ISSUE TITLE
SD Gundam Gaiden - Knight Gundam Monogatari 2 - Hikari no Knight   Save  Issues

### ISSUE THREAD

**Issue by yuya495** [quietust/nintendulator#3]
SD Gundam Gaiden - Knight Gundam Monogatari 2 - Hikari no Knight (Japan) creates SRAM file
Data cannot be saved normally

SD Gundam Gaiden - Knight Gundam Monogatari 2 - Hikari no Knight (Japan) はSRAM ファイルが作成されますが正常にデータの保存ができません

![amarec(20200507-231628)](https://user-images.githubusercontent.com/8580180/81307175-57877280-90bb-11ea-925e-e87e4fee0046.PNG)

**Comment by yuya495** [comment]
The emulator uses Nintendulator v0.985 Beta (last updated 2020-05-05 21:22:39) from Quietust's official website.

エミュレーターは、Quietustの公式WebサイトにあるNintendulator v0.985 Beta（最終更新日2020-05-05 21:22:39）を使用しています。

![amarec(20200510-045740)](https://user-images.githubusercontent.com/8580180/81483681-f73f2f00-927a-11ea-9e39-045bf68fd042.PNG)
![amarec(20200508-222737)](https://user-images.githubusercontent.com/8580180/81410166-41d98200-917b-11ea-82ab-afde8da1909f.PNG)
![amarec(20200508-222232)](https://user-images.githubusercontent.com/8580180/81410176-443bdc00-917b-11ea-8312-452dcb7e6710.PNG)
I could not save even if I set it to NES 2.0 by referring to the above site

上記サイトを参考にNES 2.0に設定しても保存できませんでした

**Comment by yuya495** [comment]
I thought that there is a possibility that the ROM could not be dumped normally, I also tried rom_checker_, but the ROM was good

ROMが正常にダンプされない可能性があると思い、rom_checker_も試してみましたが、ROMは良かったです
![amarec(20200508-224231)](https://user-images.githubusercontent.com/8580180/81411359-39824680-917d-11ea-99b7-d43bbc4a203e.PNG)

**Comment by yuya495** [comment]
State save just before making a normal save

通常のセーブをする直前のステートセーブです

[SD Gundam Gaiden - Knight Gundam Monogatari 2 - Hikari no Knight.zip](https://github.com/quietust/nintendulator/files/4603825/SD.Gundam.Gaiden.-.Knight.Gundam.Monogatari.2.-.Hikari.no.Knight.zip)

**Comment by yuya495** [comment]
I tried a normal save with mapper159
It will be saved, but the way it is saved is strange
Normally, if you start with the data of game 1, it will be saved in game 1, but for some reason it will be saved in both game 1 and game 2 at the same time

mapper159で通常のセーブを試してみました
セーブはされますがセーブのされ方が変です
通常はゲーム１のデータでスタートした場合はゲーム１に保存されますがなぜかゲーム１とゲーム２の両方に同時にセーブされます

**Comment by quietust** [comment]
Something is very strange about that game - the board appears to use an X24C02P (256-byte serial EEPROM), but the game code communicates with it using the X24C01P (128-byte serial EEPROM)'s distinctly different protocol, and as a result it fails to save anything.

Running it as mapper 159 allows it to save/load successfully, but it ends up with both save slots appearing to contain the same data (since each slot is 128 bytes). When the game attempts to Save, its code actively masks off the upper Address bit (to treat it as the Read/Write bit), so I don't see how it could possibly support 256 bytes of save data...

**Comment by yuya495** [comment]
After all the save bug of this game
To cure
Is it difficult?

やはりこのゲームのセーブバグを
治すのは
難しそうですか？

I tried saving this game and it saved successfully
Nestopia and BizHawk are the only NES emulators

私がこのゲームのセーブを試して正常にセーブできた
ファミコンエミュレーターは NestopiaとBizHawkだけでした

**Comment by quietust** [comment]
I figured out the problem and have uploaded a fixed version - apparently, the game supports both 128-byte and 256-byte EEPROMs and dynamically detects the type at startup, and I wasn't correctly emulating the method it used to distinguish them.

**Comment by yuya495** [comment]
quietust Thank you very much for doing a very good job
