### ISSUE TITLE
graphic bug of Saint Seiya - Ougon Densetsu Kanketsu Hen (Japan) issue

### ISSUE THREAD

**Issue by yuya495** [quietust/nintendulator#4]
Quietust's Hello
The emulator uses Nintendulator v0.985 Beta (last updated 2020-05-20 16:22:49) from Quietust's official website.

Quietustさんこんにちは
エミュレーターは、Quietustの公式WebサイトにあるNintendulator v0.985 Beta（最終更新日2020-05-20 16:22:49）を使用しています。

Nintendulator has the same bug as this video
https://www.youtube.com/watch?v=Mbk4yeMyPfQ
Nintendulatorでもこの動画と同じバグが発生します
![amarec(20200521-154557)](https://user-images.githubusercontent.com/8580180/82531427-5ace3400-9b7a-11ea-9858-6f596ab69f7e.PNG)

got these graphic after using second skill of siryuu.
これらのグラフィックは、siryuuの2番目のスキルを使用した後に取得しました。

**Comment by yuya495** [comment]
State save just before a graphic bug occurs
グラフィックバグが発生する直前のステートセーブです
[Saint Seiya - Ougon Densetsu Kanketsu Hen.zip](https://github.com/quietust/nintendulator/files/4660966/Saint.Seiya.-.Ougon.Densetsu.Kanketsu.Hen.zip)

**Comment by yuya495** [comment]
![amarec(20200521-161740)](https://user-images.githubusercontent.com/8580180/82533637-a8e53680-9b7e-11ea-97b3-19e5b0f9d226.PNG)
![amarec(20200521-161705)](https://user-images.githubusercontent.com/8580180/82533657-b13d7180-9b7e-11ea-9fc1-e55837b8e781.PNG)
![amarec(20200521-223344)](https://user-images.githubusercontent.com/8580180/82564273-743fa200-9bb3-11ea-8fc2-5e075f3fb609.PNG)

I tried rom check again this time
I couldn't solve it by referring to the above site

今回もロムチェックを試したり
上記のサイトを参考にしても解決できませんでした

**Comment by yuya495** [comment]
I couldn't determine the cause of this bug
I want quietust to fix this bug
I have high expectations

私はこのバグの原因を特定することができませんでした
私はquietustさんがこのバグを修正してくれるのを
とても期待しています

**Comment by quietust** [comment]
The problem you're seeing is due to a bug in the game itself - it tries to write to palette memory while rendering is in progress. Based on behavior from Visual 2C02, I think I've got a fix for this.

**Comment by yuya495** [comment]
I tested Saint Seiya-Ougon Densetsu Kanketsu Hen (Japan) with Nintendulator v0.985 Beta (last updated 2020-05-27 18:42:42) and the bug was fixed.
Thank you Quietust, this is a very good job.

Nintendulator v0.985 Beta (last updated 2020-05-27 18:42:42)を使ってSaint Seiya - Ougon Densetsu Kanketsu Hen (Japan)をテストしたところバグは治っていました
Quietustさん本当にありがとうとても良い仕事です
