### ISSUE TITLE
Linux/libretro port? 

### ISSUE THREAD

**Issue by MetalMaxMX** [quietust/nintendulator#9]
Hi! I was raising this issue more as a request/possibility to be raised in the future. Discovered this emulator fairly recently due to some posts at the nesdev forums but found that there is no Linux or libretro port of it. I would like to know the author thoughts and blockers for this to happen (and maybe other platforms as well?)

Cheers!
MetalMaxMX.

**Comment by quietust** [comment]
I currently have no plans to port Nintendulator to any other platforms, since it appears to work well enough in Wine.
